### ISSUE TITLE
No Git menu in Frescobaldi 3 on Mac

### ISSUE THREAD

**Issue by dliessi** [wbsoft/frescobaldi#1086]
If I run Frescobaldi from the Git repository I see the Git menu only when using the `v2.x` branch and not with the `master` branch.

@wbsoft Given this and #1073 I think that there is some serious problem with the menus.
I really need some input from you or @uliska, @fedelibre, @PeterBjuhr: I cannot even find out where the problem is.

**Comment by dliessi** [comment]
As I wrote in #1073 these menu issues block any progress on Mac.

**Comment by uliska** [comment]
I will try to look into that (hopefully tonight) but I have no idea if I am the right person for this type of issue.
-- 
Diese Nachricht wurde von meinem Android-Gerät mit K-9 Mail gesendet.

**Comment by uliska** [comment]
I've added a debug print to the branch `debug/git-menu` to see whether the problem is in the first stage (determining if Frescobaldi is run from Git). WRT to the other open issues I rather suspect the problem is with those menus that are imported from other files but we should rule that first thing out first.

**Comment by dliessi** [comment]
```
$ python3.6 frescobaldi

Is Frescobaldi run from Git?
True

$
```

**Comment by uliska** [comment]
I'm not 100% sure (because it's all C++) but I think [this StackOverflow issue](https://stackoverflow.com/questions/26004830/qt-change-application-qmenubar-contents-on-mac-os-x) is very much related to what we have.

It states that on OS X it is *mandatory* that added menus have active actions *before being added to the parent*.

Please check if the update to the branch makes a difference.
If this should fix the issue I'm not sure anymore it will help with #1073, though

**Comment by dliessi** [comment]
It's still not working.
I'll see if a fix similar to the one I proposed for #1073 solves the issue.

**Comment by dliessi** [comment]
Actually your fix was a good idea, but there was a mistake in the argument to QAction.
Instead of pushing the fix to your branch, I pushed a new branch `debug/issue1086`, removing the commit with the debug print instructions, fixing your solution, adding a comment in place and reformatting the commit.

Can you test if everything still works on Linux?
Also in this case I expect it to work on all systems, but, again, you never know.

Of course feel free to rephrase the comment and the commit message to your liking, before pushing to master.

**Comment by uliska** [comment]
Seems to work properly here too.
